#Create the service
kind: Service
apiVersion: v1
metadata:
  name: lbg4-api
spec:
  type: LoadBalancer
  selector:
    app: lbg4-api
  ports:
  - protocol: TCP
    port: 5000        # Defines the Service's port within the cluster
    targetPort: 5000  # Defines the Pod's port
---
#Create the pod
apiVersion: v1
kind: Pod
metadata:
  name: lbg4-api
  labels:
    app: lbg4-api
spec:
  containers:
  - name: lbg4-api
    image: gcr.io/lbg-210322/karenb-lbg-image2:jenkins-Sprint2-19
    ports:
    - containerPort: 5000
